# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc3de202ec2976771700f2eec941e6e32c32675b57848c031a89f775db28d0acad7cd159b0add7b7c3761eb7e9bd5b4182c301f194375ae42610ab623d4373a3

test:
  secret_key_base: e1d6cd7e018f4e140f174771b0bca392aff184cb286635dbd018e20e8fe008bb1389a5ed23fe33971097457a784f29d71a41cea9ecd6594c03d599b6d1b773e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
